image: node:13.8

services:
  - couchdb:3.0.0

variables:
  REACT_APP_COUCHDB_HOST: couchdb
  REACT_APP_COUCHDB_PORT: 5984
  REACT_APP_COUCHDB_DB: cards

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - validate
  - build
  - analyze

cache:
  paths:
    - node_modules/

install:
  stage: .pre
  tags:
    - Docker

  script: yarn


typecheck tests:
  stage: validate
  tags:
    - Ubuntu 18.04

  script:
    - yarn tsc


test unit:
  stage: validate
  tags:
    - Docker

  script:
    - yarn
    - yarn test-junit

  artifacts:
    reports:
      junit: test-report.xml
    paths:
      - test-report.xml


check format:
  stage: validate
  tags:
    - Docker

  script:
    - yarn
    - yarn check-format

build:
  stage: build
  tags:
    - Docker

  script:
    - yarn
    - yarn build

  artifacts:
    paths:
      - build


source_map:
  stage: analyze
  tags:
    - Docker

  script:
    - yarn
    - yarn explore --html source-map-explorer.html

  artifacts:
    expose_as: 'source map explorer'
    paths:
      - source-map-explorer.html
